### ISSUE TITLE
Add adjustment memory for Alpine Term RAM

### ISSUE THREAD

**Issue by poisongod** [FakeRajbhx/alpine-term#1]
If you are still maintaining this project, please add the ram adjustment function for it
I stick with Alpine Term because of its many features, such as left-swiping to see the QEMU console and four serial terminals.
Even though you released Vshell, it limited me a lot. It doesn't have as many terminal interfaces as Alpine Term does with the left-swipe screen, and there aren't as many customizable virtual disks and Cdrom interfaces in the Data directory, so I stick with Alpine Term V1.16.0.
I downloaded the virtual disk with Arch Linux installed in the (https://archive.org/details/software) software library where you released Alpine Term V14.0 and replaced the virtual disk file in the installation package to my Android
The last
I seem to prefer Arch Linux to Alpine Linux
This is what I would like to get feedback on, if you are lucky enough to see it and are maintaining this project. Please take my advice
Oh, sorry, my English is not very good
![Screenshot_20220222_111905](https://user-images.githubusercontent.com/90960225/155056971-3f5f6b61-ad02-46ac-a7f5-7b6c4bffb859.jpg)
![Screenshot_20220222_111940](https://user-images.githubusercontent.com/90960225/155056978-db894162-b25f-4f80-9a00-db21dc2275b1.jpg)

**Comment by XYZliang** [comment]
@[poisongod](https://github.com/poisongod)
您好，我有些问题：
我在我的三星S8上运行了这个 alpine-term ，还是挺慢的，我发现似乎不是内存限制了alpine的发挥，而是cpu。当alpine进行一些稍微大一些的任务时（例如apk添加软件），虚拟机内的cpu直接就100%了，而S8的8核CPU里只有一个核心在积极工作（100%），其他7个核心和正常待机一样。
所以如何让alpine-term调用所有手机的核心？我只是想在限制的安卓手机上运行一个docker~
另外，作者的文档中有这个一个qemu命令balloon，似乎是调整内存限制的命令，相见最后：


Hello, I have some questions:
I ran this alpine term on my Samsung S8, which is still very slow. I found that it seems that it is not the memory that limits the play of alpine, but the CPU. When Alpine performs some slightly larger tasks (such as adding software by APK), the CPU in the virtual machine is directly 100%, while only one core in the 8-core CPU of S8 is working actively (100%), and the other seven cores are the same as normal standby.
So how to make Alpine term call the core of all mobile phones? I just want to run a docker on restricted Android phones~
In addition, there is a QEMU command balloon in the author's document, which seems to be a command to adjust the memory limit:

> Limiting RAM usage
You can limit RAM usage by configuring VirtIO Balloon device through QEMU monitor. See an example below how to limit memory usage to 350 MiB:
balloon 350
If guest operating system uses less memory than specified value, QEMU will de-allocate host RAM and update visible memory size for the virtual machine. In other cases virtual machine may not release used memory or do that partially.
Some kernels or custom operating systems may not support this feature.

**Comment by rajbhx** [comment]
Ask here https://t.me/termux24x7

**Comment by poisongod** [comment]
> 
Alpine Term uses TCG acceleration, meaning TCG parameters can be changed to get more CPUCore, but only one CPUCore seems to be available for devices without ROOT
TCG parameters can be edited in the dex file of the installation package
But I didn't find the parameters for setting RAM memory in the dex file of the installation package
![Screenshot_20220226_094308](https://user-images.githubusercontent.com/90960225/155824050-4b5ebc05-e205-4a9a-a5aa-9b3751a0b24f.jpg)

**Comment by 412111959** [comment]
@XYZliang 靓仔,你还在搞这个Alpine Term吗,我有个问题,我现在提示磁盘不足,好像默认只分配了3.9g,然后用完就提示内存不足了,没有吃完手机的存储. 有什么办法扩容吗

**Comment by zhang-chao-git** [comment]
> @XYZliang靓仔，你还在搞这个Alpine Term吗，我有一个问题，我现在提示磁盘不足，好象默认只配了3.9g，然后用完就提示内存的不足了，没有吃完。有什么办法宽容吗

请问这个有解决方法吗

**Comment by oocvlp3883** [comment]
@zhang-chao-git 没有，放弃了，云服务器更省事，不折腾了，手机这个Alpine Term弊端蛮大的。效率慢，而且操作不方便

**Comment by 412111959** [comment]
@zhang-chao-git 没有，放弃了，云服务器更省事，不折腾了，手机这个Alpine Term弊端蛮大的。效率慢，而且操作不方便
