### ISSUE TITLE
There is a problem with your repository and organization

### ISSUE THREAD

**Issue by ghost** [FakeRajbhx/alpine-term#3]
Hi there!

I understand your intentions to keep projects like "Alpine Term" and "vShell" available, but you are impersonating `@xeffyr` without appropriate permission. Therefore I kindly request you (@rajbhx) to take down the GitHub organization https://github.com/xeffyr created by you. If you want to keep repositories, please transfer them under your account or organization with a *different* name.

On side note: while "Alpine Term" and "vShell" were open source projects, you are not allowed to take over the maintainership without making a fork. You are also violating the GPL-3.0 license by not providing the source code under these repositories:
* https://github.com/xeffyr/alpine-term
* https://github.com/xeffyr/android-vshell

Please, stop!

**Comment by rajbhx** [comment]
👍 done bro

**Comment by ghost** [comment]
Thank you.
