### ISSUE TITLE
Remove Termux telegram group from Readme

### ISSUE THREAD

**Issue by sylirre** [FakeRajbhx/alpine-term#5]
You specify the official Telegram group in the [README section](https://github.com/FakeRajbhx/alpine-term#official-telegram-group). However the Alpine Term project **was never developed or supported by Termux organization**. As maintainer of @termux I kindly request to remove our support links from your [README](https://github.com/FakeRajbhx/alpine-term/blob/main/README.md) file.

![Screenshot_20230401_094738](https://user-images.githubusercontent.com/107305601/229270513-7c1f54c1-66a4-419d-9850-58aa43911be5.png)

From time to time confused users came into our Telegram group and post Alpine Term bugs which are not relevant to our project. That's not good.

**Comment by rajbhx** [comment]
Done #6

**Comment by rajbhx** [comment]
👍

**Comment by sylirre** [comment]
Thanks
